### ISSUE TITLE
HTTP Request Timeout

### ISSUE THREAD

**Issue by prowebuk** [Swarkin/Godot-AwaitableHTTPRequest#10]
Thanks for the great plugin, is it possible to set a HTTP request timeout value?

**Comment by Swarkin** [comment]
Yeah, just set the value in the inspector or do it trough a script:
![image](https://github.com/user-attachments/assets/9d9510a0-2c1b-4d85-9b33-b445b12de74b)

**Comment by prowebuk** [comment]
Thanks for the swift reply, I'm instantiating in script as per your example: @export var http: AwaitableHTTPRequest
So don't have a node to inspect.. sorry if I'm being a bit of a noob :-)

**Comment by Swarkin** [comment]
`http.timeout = 10.0`

**Comment by prowebuk** [comment]
Perfect thanks
