### ISSUE TITLE
Arguments for async_request() different order than request()

### ISSUE THREAD

**Issue by tobtobxx** [Swarkin/Godot-AwaitableHTTPRequest#3]
The arguments for `HTTPRequest.request()` are:
```
Error request(url: String, custom_headers: PackedStringArray = PackedStringArray(), method: Method = 0, request_data: String = "") 
```
[docs](https://docs.godotengine.org/en/4.3/classes/class_httprequest.html#class-httprequest-method-request)

The arguments for `AwaitableHTTPRequest.async_request()` are:
```
HTTPResult async_request(url: String, method := HTTPClient.Method.METHOD_GET, custom_headers := PackedStringArray(), request_body := ''):
```

This is kinda annoying when just replacing HTTPRequest with it. Only a little though. Your call whether to change it.

**Comment by Swarkin** [comment]
Hi, I see what you mean and I'll likely change it soon, thanks for showing!
